echo ""
GREEN='\033[0;32m'
NC='\033[0m'
BOLD='\033[1m'
echo -e "${GREEN}${BOLD}BBBBBBBBBBBBBBBB      "
echo "B:::::::::::::::B     "
echo "B:::::BBBBBB:::::B    "
echo "B:::::B     B:::::B   "
echo -e "B:::::B     B:::::B  ${GREEN}rrrrr   rrrrrrrr"
echo -e "${BOLD}B:::::B     B:::::B  ${GREEN}r::::rrr::::::::r"
echo -e "${BOLD}B:::::BBBBBB:::::B   ${GREEN}r::::::::::::::::r"
echo -e "${BOLD}B::::::::::::::BB    ${GREEN}rr::::::rrrr::::::r"
echo -e "${BOLD}B:::::BBBBBB:::::B    ${GREEN}r:::::r    r:::::r"
echo -e "${BOLD}B:::::B     B:::::B   ${GREEN}r:::::r    rrrrrrr"
echo -e "${BOLD}B:::::B     B:::::B   ${GREEN}r:::::r"
echo -e "${BOLD}B:::::B     B:::::B   ${GREEN}r:::::r"
echo -e "${BOLD}B:::::BBBBBB:::::B    ${GREEN}r:::::r"
echo -e "${BOLD}B:::::::::::::::B     ${GREEN}r:::::r"
echo -e "${BOLD}BBBBBBBBBBBBBBBB      ${GREEN}rrrrrrr"
echo ""
echo -e "                      ${GREEN}${BOLD}BBBBBBBBBBBBBBBB     "
echo -e "                      B:::::::::::::::B    "
echo -e "                      B:::::BBBBBB:::::B   "
echo -e "                      B:::::B     B::::B     ${GREEN}aaaaaaaaaaaaa"
echo -e "                      ${BOLD}B:::::B     B::::B     ${GREEN}a::::::::::::a"
echo -e "                      ${BOLD}B:::::B     B::::B     ${GREEN}aaaaaaaaa:::::a"
echo -e "                      ${BOLD}B:::::BBBBBB::::B               ${GREEN}a::::a"
echo -e "                      ${BOLD}B:::::::::::::BB         ${GREEN}aaaaaaa:::::a"
echo -e "                      ${BOLD}B:::::BBBBBB::::B      ${GREEN}aa::::::::::::a"
echo -e "                      ${BOLD}B:::::B     B::::B    ${GREEN}a::::aaaa::::::a"
echo -e "                      ${BOLD}B:::::B     B::::B   ${GREEN}a::::a    a:::::a"
echo -e "                      ${BOLD}B:::::B     B::::B   ${GREEN}a::::a    a:::::a"
echo -e "                      ${BOLD}B:::::BBBBBB::::B    ${GREEN}a:::::aaaa::::::a"
echo -e "                      ${BOLD}B::::::::::::::B      ${GREEN}a::::::::::aa:::a"
echo -e "                      ${BOLD}BBBBBBBBBBBBBBB        ${GREEN}aaaaaaaaaa  aaaa"
echo -e "${NC}"
